name: Daily Discord Image

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  post-image:
    runs-on: ubuntu-latest
    steps:
      - name: Post image to Discord
        run: |
          curl -X POST "${{ secrets.DISCORD_WEBHOOK }}" \
            -H "Content-Type: application/json" \
            -d '{
              "username": "Waker",
              "embeds": [{
                "title": "Goodmorning.",
                "image": {
                  "url": "https://cdn.discordapp.com/attachments/1482807222210662453/1515925622877192252/IMG_4990.jpg?ex=6a30c741&is=6a2f75c1&hm=1edb48dd09a1d56c6522a41c7a4d286dd8c0079105c536b2ed3628d2becb1f92&"
                }
              }]
            }'
